#!/bin/bash
# Gather all files together into ~/rpmbuild and build the rpm package
# Precondition is an rpmbuild folder structure and rpmbuild itself
RPMBUILD=~/rpmbuild
read_version
VERSION=$(<version)
echo Building version "$VERSION"

if rpm -qa rpmdevtools | grep rpmdevtools; then
  echo "Found rpmdevtools"
else
  echo "Missing rpmdevtools. Please install them first."
  exit 1
fi

if [[ ! -d "$RPMBUILD" ]]; then 
  echo "Missing $RPMBUILD. Create it now..."
  rpmdev-setuptree
fi

if [[ ! -d "$RPMBUILD" ]]; then 
  echo "Could not create $RPMBUILD !"
  exit 1
fi

SOURCES=~/rpmbuild/SOURCES
SPECS=~/rpmbuild/SPECS
DEST=$SOURCES/fow-$VERSION
LIB=$DEST/lib
BIN=$DEST/bin
MAN=$DEST/man

if [[ ! -d "$SOURCES" ]]; then 
  echo "Could not find $SOURCES"
  exit 1
fi

if [[ -d "$DEST" ]]; then
  echo "Remove existing $DEST"
  rm -r "$DEST"
fi

mkdir "$DEST"
mkdir "$LIB"
mkdir "$BIN"
mkdir "$MAN"

cp script/fow "$BIN"
cp fow/* "$LIB"
cp man/* "$MAN"

cp fow.spec.template "$SPECS/fow.spec"
sed -i "s/__VERSION__/${VERSION}/g" "$SPECS/fow.spec"

cd "$SOURCES" && tar -czf fow-$VERSION.tar.gz "fow-$VERSION"

rpmbuild -ba "$SPECS/fow.spec"

RPM=$(find ~/rpmbuild/RPMS/ -name fow-$VERSION-*.rpm)

echo Done.
echo Now you can install th rpm on your local machine as sudo:
echo rpm -ivh $RPM

